server:
  port: 8004

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3308/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*:xml
  type-aliases-package: com.atguigu.gulimall.product.entity
  global-config:
    db-config:
      id-type: auto
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
